version: '3.9'
services:
  two_factor_authenticate:
    container_name: authenticate_project
    build: .
    ports: 
      - "8001:8001"
    volumes: 
      - .:/app:rw
    restart: "no"
    command: sh
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true